# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 348699678f54852fadc2543e587f94608d40210620538dee9a15023b1e385cd8351aa214d33926110574bbd887122457a55b0f053f8c380d3c1a216b9d0be0d0

test:
  secret_key_base: c374710ade6fd28292b0d7dc6c7b11de21a3de58104716c3fdfbfd86e64062bb1db8fbedd972cf8e4d0078efc7210404c52968862c24344cc5ce1fbc42fce8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
